<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="NewFolder\**" />
      <EmbeddedResource Remove="NewFolder\**" />
      <None Remove="NewFolder\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\C4Sharp\C4Sharp.csproj" />
    </ItemGroup>

</Project>
