@startuml container-diagram-for-internet-banking-system-v2-c4container
!include <C4/C4_Container>

UpdateElementStyle("system", $bgColor=#D4E6F1,$fontColor=#1A5276,$borderColor=#1A5276,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_system", $bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateElementStyle("person", $bgColor=#797D7F,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("component", $bgColor=#FAE5D3,$fontColor=#CA6F1E,$borderColor=#CA6F1E,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_component", $bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateElementStyle("container", $bgColor=#EAF2F8,$fontColor=#2E86C1,$borderColor=#2E86C1,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_container", $bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateBoundaryStyle($elementName=system,$bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=container,$bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=enterprise,$bgColor=#F8F9F9,$fontColor=#797D7F,$borderColor=#797D7F,$shadowing="false",$shape=RoundedBoxShape())
SHOW_PERSON_PORTRAIT()
LAYOUT_TOP_DOWN()

title Container diagram for Internet Banking System v2

Person_Ext(Customer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")
System(BankingSystem, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
System_Ext(MailSystem, "E-mail system", "The internal Microsoft Exchange e-mail system.")

System_Boundary(c1, "Internet Banking") {
    Container(WebApp, "WebApp", "Web Application:C#, WebApi", "Delivers the static content and the Internet banking SPA")
    Container(Spa, "Spa", "Spa:JavaScript, Angular", "Delivers the static content and the Internet banking SPA")
    Container(MobileApp, "Mobile App", "Mobile:C#, Xamarin", "Provides a mobile banking experience")
    ContainerDb(SqlDatabase, "SqlDatabase", "Database:SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
    ContainerQueue(RabbitMQ, "RabbitMQ", "Queue:RabbitMQ", "Stores user registration information, hashed auth credentials, access logs, etc.")
    Container(BackendApi, "BackendApi", "Api:Dotnet, Docker Container", "Provides Internet banking functionality via API.")
}


Rel(Customer, WebApp, "Uses", "HTTPS")
Rel(Customer, Spa, "Uses", "HTTPS")
Rel(Customer, MobileApp, "Uses")
Rel_Neighbor(WebApp, Spa, "Delivers")
Rel(Spa, BackendApi, "Uses", "async, JSON/HTTPS")
Rel(MobileApp, BackendApi, "Uses", "async, JSON/HTTPS")
Rel_Back_Neighbor(SqlDatabase, BackendApi, "Uses", "async, JSON/HTTPS")
Rel_Back(RabbitMQ, BackendApi, "Uses", "async, JSON")
Rel_Back(Customer, MailSystem, "Sends e-mails to")
Rel_Back(MailSystem, BackendApi, "Sends e-mails using", "sync, SMTP")
Rel_Neighbor(BackendApi, BankingSystem, "Uses", "sync/async, XML/HTTPS")
@enduml
