@startuml system-context-diagram-for-internet-banking-system-c4deployment
!include ../.c4s/C4_Deployment.puml

UpdateElementStyle("system", $bgColor=#1a67be,$fontColor=#FFFFFF,$borderColor=#175eaa,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_system", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateElementStyle("person", $bgColor=#0d437b,$fontColor=#FFFFFF,$borderColor=#0d437b,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("component", $bgColor=#85bbf0,$fontColor=#000000,$borderColor=#78a8d9,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_component", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateElementStyle("container", $bgColor=#438dd4,$fontColor=#FFFFFF,$borderColor=#3e82c5,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=2)
UpdateElementStyle("external_container", $bgColor=#999999,$fontColor=#FFFFFF,$borderColor=#8a8a8a,$shadowing="false",$shape=RoundedBoxShape(),$borderStyle=SolidLine(),$borderThickness=1)
UpdateBoundaryStyle($elementName=system,$bgColor=#FFFFFF,$fontColor=#000000,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=container,$bgColor=#FFFFFF,$fontColor=#000000,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
UpdateBoundaryStyle($elementName=enterprise,$bgColor=#FFFFFF,$fontColor=#000000,$borderColor=#000000,$shadowing="false",$shape=RoundedBoxShape())
SHOW_PERSON_PORTRAIT()
LAYOUT_TOP_DOWN()

title System Context diagram for Internet Banking System


Deployment_Node(plc, "Big Bank plc", "Big Bank plc data center") {
    Deployment_Node(dn, "bigbank-api***	x8", "Ubuntu 16.04 LTS") {
        AddProperty("Java Version", "8")
        AddProperty("Xmx", "512M")
        AddProperty("Xms", "1024M")
        Deployment_Node(apache, "Apache Tomcat", "Apache Tomcat 8.x") {
        Container(BackendApi, "BackendApi", "Api:Dotnet, Docker Container", "Provides Internet banking functionality via API.")
        }
    }
    Deployment_Node(bigbankdb01, "bigbank-db01", "Ubuntu 16.04 LTS") {
        Deployment_Node(oracle, "Oracle - Primary", "Oracle 12c") {
        ContainerDb(Database.1, "OracleDatabase", "Database:Oracle Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
        }
    }
    Deployment_Node(bigbankdb02, "bigbank-db02", "Ubuntu 16.04 LTS") {
        Deployment_Node(oracle2, "Oracle - Primary", "Oracle 12c") {
        ContainerDb(Database.data.reader, "OracleDatabase", "Database:Oracle Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
        }
    }
    Deployment_Node(bb2, "bigbank-web***	x4", "Ubuntu 16.04 LTS") {
        AddProperty("Java Version", "8")
        AddProperty("Xmx", "512M")
        AddProperty("Xms", "1024M")
        Deployment_Node(apache2, "Apache Tomcat", "Apache Tomcat 8.x") {
        Container(Corporate.Finance.Limits.Service.ServiceBus, "WebApp", "Web Application:C#, WebApi", "Delivers the static content and the Internet banking SPA")
        }
    }
}

Deployment_Node(ios, "Customer's mobile device", "Apple IOS") {
Container(MobileApp, "MobileApp", "Mobile:C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
}

Deployment_Node(computer, "Customer's computer", "Mircosoft Windows and Apple macOS") {
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Apple Safari or Microsoft Edge") {
    Container(Spa, "SPA", "Spa:JavaScript, Angular", "Provides all the Internet banking functionality to customers via their web browser")
    }
}

Rel(MobileApp, BackendApi, "Makes API calls to", "json/HTTPS")
Rel(Spa, BackendApi, "Makes API calls to", "json/HTTPS")
Rel_U(Corporate.Finance.Limits.Service.ServiceBus, Spa, "Delivers to the customer's web browser")
Rel(BackendApi, Database.1, "Writes to", "JDBC")
Rel_Back(BackendApi, Database.data.reader, "Reads from", "JDBC")
Rel_R(Database.1, Database.data.reader, "Replicates data to", "JDBC")
@enduml
